[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
smartcontract = "7FaYpf16DM4z6mAZUMvtqUSQgxjW6RQJ4N7uGMSxSwr3"

[programs.localnet]
smartcontract = "7FaYpf16DM4z6mAZUMvtqUSQgxjW6RQJ4N7uGMSxSwr3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/yobel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
