[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
smartcontract = "Aq4XKH5oLKUNDwxDqD7RDyYz76ZqY3HP1ttb8KW9HMop"

[programs.localnet]
smartcontract = "Aq4XKH5oLKUNDwxDqD7RDyYz76ZqY3HP1ttb8KW9HMop"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/yobel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
