[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
smartcontract = "E4ToFZT9sWoMewsLiVKweYt2QRHwUFBZ2dJcw92br2Dx"

[programs.localnet]
smartcontract = "E4ToFZT9sWoMewsLiVKweYt2QRHwUFBZ2dJcw92br2Dx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/yobel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
