[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
smartcontract = "GVVMixtE5VECdKHJzaJSMgbFNjifwmJTLgb4skuwDeMK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yobel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
